### ISSUE TITLE
Datasource filtering not working

### ISSUE THREAD

**Issue by zooshme** [DeuxHuitHuit/entry_relationship_field#11]
I'm trying to filter all comments for a particular article. Each comment uses a relationship field to associate it to a particular article. In the datasource I pass on the the url parameter that is the article id to the filter for the relationship field. The resulting datasource contains no entries though. When I use Select Box Link, or Association Field I get the expected comments. Is datasource filtering implemented in your extension yet?

Many thanks.

**Comment by nitriques** [comment]
> Is this not possible?

Right now, it is not. We can only filter on entry ids.

The feature you want requires filtering things based on other fields value and that's kind of complicated right now in Symphony. But it's on the feature list :)

**Comment by nitriques** [comment]
@munki-boy 

> I have section "project type" and section "project". Project contains an ERF to Project Type (each project is of a type). I want to DS output just Projects of a certain Type.

Starting from version 1.0.2, it would be feasible, but you would need two datasources.

1. project types filtered by type: you select the entry ids of types as output parameter.
1. project filtered by $ds-project-types-filtered-by-type.id: you select the field you want to have.

That way, you filter with other fields (input, textbox, ...) to get the ids and then filter the actual data using the resulting ids.

@zooshme 

I'll mark this one fix as adding more intelligent filtering is on the roadmap.

**Comment by munki-boy** [comment]
@nitriques this is good because you could do it if the output was getting too large.  I've been filtering in the xslt so far with my small data project. 

I'm now interested in a backend search/selector instead of full list of entries since "filter entries" isn't in Symphony 2.6.2? Getting a bit slow when I do "Link to Entry" with 400+ items in list.

**Comment by munki-boy** [comment]
Loving the extension on the whole really fast to input stuff.

**Comment by nitriques** [comment]
:) 

> I'm now interested in a backend search/selector instead of full list of entries since "filter entries" 

I'd very like to be able to reuse this. Also support paging...

Feel free to poke the code and ask for help ;)
