### ISSUE TITLE
Show the minimum and the maximum of entries

### ISSUE THREAD

**Issue by aVandalInShorts** [DeuxHuitHuit/entry_relationship_field#18]
I thought it could be a good idea to show th number of entries there are in the field.

If there is no minimum or maximum count : "Showing 5 entries."
If there is a minimum count but no maximum : "Showing 1 entries. Needs at least 3."
If there is a maximum count but no minimum : "Showing 10 entries. Needs no more than 3."
If there is both a maximum and a minimum count : "Showing 10 entries. Needs at least 3. Needs no more than 20."

Or a simple "Min : 3 entries. Max 6 entries".

Cheers

**Comment by nitriques** [comment]
What about this

![image](https://cloud.githubusercontent.com/assets/771169/5983304/18ae688e-a89a-11e4-8ffa-5da6a6aa8133.png)

**Comment by aVandalInShorts** [comment]
It says "sexy and smart" :+1: :guitar: :rocket: :unicorn: :hash: :open_mouth: :smile_cat:

**Comment by nitriques** [comment]
:princess: :ear: :boar: :maple_leaf: :ribbon: :rice_ball: :two: :eight: :eight:
