### ISSUE TITLE
Add XSLT template for the header as well

### ISSUE THREAD

**Issue by andrewminton** [DeuxHuitHuit/entry_relationship_field#29]
Is there scope to effect the heading of each Entry Relationship block using the XSL templates at all?

With textareas it's starting to look very cluttered when editing an entry in a section.

Was just looking at how Craft deal with their Matrix field and it feels similar to ERF: http://buildwithcraft.com/docs/matrix-fields#the-field

Especially the bit about when an Entry Relation is open.. the content is inside, when it's collapsed we see a snippet of the content in the gray bar which is also knocked back to a gray colour text so as not to stand out/be too prominent.

**Comment by nitriques** [comment]
This is not possible at the moment and I do not know how to implement it... It's a great idea though!!

I think that the easiest way (for me) to do it would be to expose the 'deepness' level (and other parent values) into the backend xml...

**Comment by nitriques** [comment]
> I think that the easiest way (for me) to do it would be to expose the 'deepness' level (and other parent values) into the backend xml...

This has been kind of done :) https://github.com/DeuxHuitHuit/entry_relationship_field/commit/666bb9eff7abb2b2ee292e4bef9883144271622b#diff-74f76b2010f612ced4f5aaa77da364f8R543

**Comment by nitriques** [comment]
Also related to #30

You will be able to create your own header using those...

**Comment by nitriques** [comment]
@andrewminton If you could test this feature as well, it would be awesome!

**Comment by andrewminton** [comment]
Wooop!

I'll give it a spin now. So far so good on the other aspects.

**Comment by nitriques** [comment]
:+1:
