### ISSUE TITLE
Selecting more than one relationship before save bug

### ISSUE THREAD

**Issue by andrewminton** [DeuxHuitHuit/entry_relationship_field#37]
I'm using the Dev branch with Symphony 2.6beta2 and experience a weird UI behaviour before saving the main section.

Main section is an article with an ERF linked to an images section.. I want to associate more than one image with the Article so choose 'link to entry' and associate one image as expected... then it returns to the main section no problem and the association is present in the UI. Now before saving, click 'link to entry' again and I attempt to associate another image.. this time it returns to the main section but the association does not appear in the UI... but if you save the main section, the association has actually saved.. it's just not appearing. there is an error in the JS of the extension from what I can see... in relation to https://github.com/DeuxHuitHuit/entry_relationship_field/blob/dev/assets/publish.entry_relationship_field.js#L293 ??

Could that be related maybe?

**Comment by nitriques** [comment]
Can you please give me the js error message please ? :)

**Comment by andrewminton** [comment]
Uncaught TypeError: undefined is not a function

**Comment by nitriques** [comment]
symphonyOrderable is from the core... and I am not aware of it disappearing.. I can't test right now but will have the time to do it this afternoon (it's 10:54 here right now)

**Comment by andrewminton** [comment]
Ok cool, hmmm I wonder if there were changes introduced in 2.6 which meant this changed.. will dig around. gnight :)

**Comment by nitriques** [comment]
I am currently developing it using the latest integration branch so I'll see :)

**Comment by andrewminton** [comment]
It could be updating extension related. Just removed and re-added the extension after an install/uninstall operation and it now seems to have resolved itself.. does the update script include the 'create_new' sql table maybe?

**Comment by nitriques** [comment]
> does the update script include the 'create_new' sql table maybe?

Yeah going from 1.0.1 to 1.0.2 needs a table adjustment.

**Comment by andrewminton** [comment]
Ye maybe that's it then.

**Comment by nitriques** [comment]
Great! So we can close this issue ?

Really cool new pic BTW

**Comment by andrewminton** [comment]
On my install it's fine, but my colleague still experiences this weirdness... got a feeling it could be browser cache related for the core JS somehow.

Pic, Inspired by yourself! I loves my Mountain Biking see :)

**Comment by andrewminton** [comment]
Let's close it and if it returns raise it again.

**Comment by nitriques** [comment]
Good!

**Comment by andrewminton** [comment]
Hi there,

Just so you know.. Redactor v1.1.1 was the culprit... conflicting JS effects the symphonyOrderable function somehow. will dig around and see if it can be fixed up.

**Comment by nitriques** [comment]
Ok thanks for the info! Is Redactor modifying jQuery somehow ?

**Comment by andrewminton** [comment]
Just looking at Remies repo and there is a version of jQuery included with
the extension.. 1.7 which seems to error in quite a few places.. and when
Parenthesis Tabs is in use for multilingual as well... booom! it all goes
bang.

**Comment by nitriques** [comment]
Hum for sure 1.7 is really old. Why would someone ship jQuery with their extension ? The backend depended so on it for a long time now... And we currently use 2.1.3 (which is the latest)

**Comment by andrewminton** [comment]
I know right. I'm sure it was floating around before jquery was shipped as a core library though.. so maybe it's just legacy code that hasn't been touched in a while. Still it's broken so looking to fix where I can.. unfortunately we'd need a licence to get the latest build code which would work with jQuery 2.1.3 I'd imagine.

**Comment by nitriques** [comment]
:(
