### ISSUE TITLE
Import stylesheet error

### ISSUE THREAD

**Issue by munki-boy** [DeuxHuitHuit/entry_relationship_field#44]
Hey @nitriques can you help me find out about this problem?  When I try to make a template like in your screencast it always says this error.

    XSLTProcessor::importStylesheet(): compilation error: file file:///D:/wamp/www/munki-49/ line 3 element import

It doesn't say which file where the line 3 is.  Even when my template is just like this I get the error

    <?xml version="1.0" encoding="UTF-8"?> <xsl:stylesheet version="1.0"
     xmlns:xsl="http://www.w3.org/1999/XSL/Transform"> 
         <xsl:template match="entry"> 
         </xsl:template> 
    </xsl:stylesheet>

My associated section is called "Photos", my template file is called photos.xsl

Cheers

**Comment by munki-boy** [comment]
PS I tried sym 2.6 and 2.6.2 on WAMP win8 x64

**Comment by nitriques** [comment]
What version are you running  ? And if the answer is 1.0.1, can you try the `dev` branch please ?

**Comment by munki-boy** [comment]
I think I tried both but I'll try again just to be sure

**Comment by nitriques** [comment]
Ok. 1.0.1 is far from 1.0.2beta2. So I really need to have the version you are running.

**Comment by munki-boy** [comment]
Sorry a different work problem happened I'll check and test both this evening and report back.

**Comment by nitriques** [comment]
No stress, no problems ! :smile:

**Comment by munki-boy** [comment]
:)

**Comment by munki-boy** [comment]
I just did a clean install of 2.6.2 and tried both master and dev of ERF and I do get the error:
    XSLTProcessor::importStylesheet(): compilation error: file file:///D:/wamp/www/x/ line 3 element import

**Comment by nitriques** [comment]
Hum... I've never tried it on windows....

Can you tell me:

1. The name of the section.
2. The name and realpath of the xsl file.
3. A print screen (or copy of) the field settings ?

**Comment by munki-boy** [comment]
The address there is the root folder of symphony "x" so I don't know which file the line 3 is in. Unlike above my section and template are called "Photo" and "photo.xsl".  The error only shows up if I have the photo.xsl template in the er-templates folder so it's loading it.

I have just put one text input field in my Photo section called "Title" and then put the ERF in another section called "Gallery" so it's all really simple.

**Comment by munki-boy** [comment]
Sorry I was typing to you, I'll just grab the screen now.

**Comment by munki-boy** [comment]
XSL file is here:

D:\wamp\www\x\workspace\er-templates\photo.xsl

Winderz uses the \ instead of / for the filesystem but in the URL it's normal.

**Comment by munki-boy** [comment]
![screen](https://cloud.githubusercontent.com/assets/4517581/7778905/c61ccc9c-00c7-11e5-883d-76aa5b2a3ec3.jpg)

The ERF field in the Gallery section

**Comment by nitriques** [comment]
Can you add this line

```php
var_dump($xslFilePath);die;
```

BEFORE this one: https://github.com/DeuxHuitHuit/entry_relationship_field/blob/dev/content/content.render.php#L177

And then check with firefox dev tools the xhr request response... we should see the var_dump result...

**Comment by munki-boy** [comment]
Sorry wasn't sure how to see it in FF dev, I found this in Firebug is it the same thing?

    <pre class='xdebug-var-dump' dir='ltr'><small>string</small> <font color='#cc0000'>'D:\wamp\www\x/workspace
/er-templates/photo.xsl'</font> <i>(length=46)</i>
</pre>

**Comment by nitriques** [comment]
Yes... looks related to this https://github.com/symphonycms/symphony-2/issues/2316 

Could you try this ?

https://github.com/jensscherbl/symphonycms/commit/dc211a791af9082f753fbd95edf9bcd1a23c0808

**Comment by munki-boy** [comment]
Ok, first timer, I made my file in symphony to be the same as this one:
https://raw.githubusercontent.com/jensscherbl/symphonycms/dc211a791af9082f753fbd95edf9bcd1a23c0808/symphony/lib/toolkit/class.frontendpage.php
but the XHR request stays the same and without var_dump the error is still showing.

**Comment by munki-boy** [comment]
Windows explorer (file manager) will convert D:\wamp\www\x/workspace
/er-templates/ to D:\wamp\www\x\workspace
\er-templates\ if I paste it in there but I'm pretty sure in a command shell "/" would be a switch rather than a path

**Comment by munki-boy** [comment]
I was asking about this on Gitter but I don't think I explain myself well enough for people to help

**Comment by munki-boy** [comment]
If I paste into the FF address bar I need it to be like this to find the file D:/wamp/www/x/workspace/er-templates/photo.xsl

**Comment by nitriques** [comment]
Ok changing the frontendpage class won't do anything. I've re-implemented a similar but yet different functionality.

Maybe windows explorer does things, but it's our php XSLT process who can't figure things out.

What I was trying to say is to apply the same kind of patch, but on this line https://github.com/DeuxHuitHuit/entry_relationship_field/blob/dev/content/content.render.php#L179

somehting like 

```php
<xsl:import href="' .  str_replace('\\', '/',  $xslFilePath) . '"/>
```

**Comment by nitriques** [comment]
> If I paste into the FF address bar 

It's not related to that... But yes you should be able to display the xsl file, if FF support displaying such files.

**Comment by munki-boy** [comment]
Sorry bit of a noob with these things, I tried and I can now see the photo.xsl in my backend so it has worked.  Thanks so much for all your help @nitriques will you make a version where it can work for windows as well as nix?

**Comment by nitriques** [comment]
Great! Yes I'll port the fix right now! Thanks for your time!

**Comment by munki-boy** [comment]
Thanks for yours, been wanting to play with this extension.

**Comment by nitriques** [comment]
My pleasure. See eace10e for the official fix! Thanks again!
