### ISSUE TITLE
Can't create new content with a required entry relationship

### ISSUE THREAD

**Issue by cbwl** [DeuxHuitHuit/entry_relationship_field#49]
If I have an Entry Relationship Field which is required on my section, I can't create new content in that section:

 - When I go to create the link I get an error along the lines of "Error while saving field X. Not enough parameters". I am also unable to save the entry after this even though the entry relationship field remains populated after the error pops up.
 - Equally, if I make the field non-required but then set "minimum count of entries in this field" to 1, I am able to save content without linking any entries in the field.

This is on Symphony 2.6.2. Any thoughts?

**Comment by henrysingleton** [comment]
I believe this is because of the issue where you can't assign child content to a parent that does not yet exist, as it attempts to save the child relationship immediately.

**Comment by nitriques** [comment]
Yes can you try the latest `dev` branch please ? Since the field tries to save itself via ajax, there's an error when the entry does not yet exists...

**Comment by cbwl** [comment]
Yeah latest dev seems to work well, thanks!

**Comment by nitriques** [comment]
Great. Thanks.

**Comment by henrysingleton** [comment]
I still get this issue even with the dev branch. I'm going to do more testing over the weekend but saving a child when a parent is unsaved still seems unreliable for me.

**Comment by nitriques** [comment]
Hum what Symphony version ?

**Comment by henrysingleton** [comment]
2.6.2

**Comment by nitriques** [comment]
Hum... Could you check if the ajax request returns an error ?

**Comment by henrysingleton** [comment]
My apologies, I wasn't at the head of the dev branch. I have updated now and things seem fine now. Ill do some more testing. If I run into anything I'll create a new issue. 
Thanks!

**Comment by nitriques** [comment]
Great! Thanks!
