### ISSUE TITLE
Uncaught TypeError: list.symphonyOrderable is not a function

### ISSUE THREAD

**Issue by andrewminton** [DeuxHuitHuit/entry_relationship_field#53]
Line 384. I keep getting an error with list.symphonyOrderable not kicking in so I can't re-order the relationship entries. Does this only work if I have Order entries installed? or is it just a bug? 

Thanks

**Comment by andrewminton** [comment]
Closing this.. as once again Redactor bites me in the ass! https://github.com/DeuxHuitHuit/entry_relationship_field/issues/37 Same issue.

**Comment by andrewminton** [comment]
Hmmm. Maybe not redactor. I removed it and many other extensions and this seems to still throw the error.

**Comment by nitriques** [comment]
:( 

symphonyOrderable is a core plugin so you should not need anything to make it work.

**Comment by andrewminton** [comment]
Redacator has some crazy browser caching thing with jquery going on.. even when it was disabled/uninstalled.. I stil had remnants of it's code effecting the symphonyOrderable function somehow.. resorted to editor_for_symphony instead now. :)

**Comment by nitriques** [comment]
Glad you work it out! I hope to have time to try to integrate sir trevor or medium.js as an editor this summer.

**Comment by andrewminton** [comment]
Awesome! Love Sir Trevor. Lot's of JSON to parse with that bad boy! very flexible though.

**Comment by nitriques** [comment]
Yup! And the result is semantic, not just a bunch of weird looking html

**Comment by andrewminton** [comment]
+1
