### ISSUE TITLE
Auto-generated frontend form markup incorrect

### ISSUE THREAD

**Issue by johnpuddephatt** [DeuxHuitHuit/entry_relationship_field#54]
When attaching an event to a page with an ERF, the auto-generated form renders ERF fields like this:

`<input name="fields[erf-name]" type="text" />`

However this is incorrect and does not work (results in a Symphony warning). The following appears to be correct:

`<input name="fields[erf-name][entries]" type="text" />`

**Comment by nitriques** [comment]
Thanks John!

**Comment by nitriques** [comment]
I've also made it hidden by default, since I do not think that developers should let users set this value!
