### ISSUE TITLE
Formatters and ERF datasource output

### ISSUE THREAD

**Issue by andrewminton** [DeuxHuitHuit/entry_relationship_field#55]
Not sure if this has been discussed at all, but when you include all child elements in the ERF field. Textareas with formatters do not represent the correct output desired.

I see this sort of action on my textareas:

`<content mode="">[CDATA[....#my content]]</content>`

No mode and the markdown isn't rendered as HTML for me.

Is this not catered for with ERF?

**Comment by nitriques** [comment]
I had some problems with this and it may not be 100% resolved. Can you tell me

1. What's the field's settings regarding included element
2. What's in your data-source

Thanks.

**Comment by andrewminton** [comment]
I have *.image, *.textarea and *.gallery as included element items (sections)

Here's a pastie of the DS for my page datasource: http://pastie.org/private/lu2egrnv9iglvmpzcuuuq

**Comment by nitriques** [comment]
Can you try to see what you get when you set the field's setting to *

**Comment by andrewminton** [comment]
As in change the included elements to : * in the field section editor?

If so, done that, no joy.

**Comment by nitriques** [comment]
:( And we are talking about the core Textarea Field ?

**Comment by andrewminton** [comment]
Yes correct. Core field using standard markdown extension.

**Comment by andrewminton** [comment]
Is it because we're not actually specifying the intended output with textarea:formatted in the DS?

**Comment by andrewminton** [comment]
Should we maybe spit out the `formatted` and `unformatted` modes into the DS by default? if it was left to the DS editor it may complicate the selection options too much.

**Comment by andrewminton** [comment]
If I replace `$curMode` with `formatted` on this line: https://github.com/DeuxHuitHuit/entry_relationship_field/blob/master/fields/field.entry_relationship.php#L704

The textarea outputs the formatted/escaped entity value. The values are definately there, it's just not choosing between `value` and `formatted_value` and just returns the first entry in array each time which will always be `value` I guess.

**Comment by nitriques** [comment]
Hum... can you var_dump($fieldIncludableElements) juste bfore this line: https://github.com/DeuxHuitHuit/entry_relationship_field/blob/master/fields/field.entry_relationship.php#L696

It should output ALL modes by default...

**Comment by andrewminton** [comment]
@nitriques The above returns null for me.

**Comment by nitriques** [comment]
hum.. and what's in `$curMode` ?

**Comment by andrewminton** [comment]
By placing `$curMode` on line `696` I get `string 'formatted' (length=9)` returned.

**Comment by nitriques** [comment]
So the variable contains the good information... I really wonder why the field does not produce the right value... Just to be sure: changing `$curMode` to `'formatted'` solves the problem ?

**Comment by andrewminton** [comment]
The variable outputs an escaped entity string version of the textarea field and not html markup as it does normally with other datasources when you choose `formatted` within the DS included elements.

**Comment by nitriques** [comment]
Ok. But do you have a different XML output by replacing the variable  `$curMode` (which contains 'formatted') to the hardcoded string `'formatted'` ?

**Comment by andrewminton** [comment]
![screen shot 2016-02-09 at 21 46 43](https://cloud.githubusercontent.com/assets/707189/12931672/cbfe33fc-cf76-11e5-90e7-ae8f8d10134e.png)

Not sure I understand what you mean above. I hard coded the variable `$curMode` to `'formatted'` on line `696` and the above grab of my datasource show what I see in my debug.. escaped entities instead of html tags. 

If I hard code 'formatted' in place of `$curMode` or `$subMode` in the following functions. It still returns the escaped entities seen in the screen grab.

**Comment by nitriques** [comment]
The match-element being formatted renders me clue less...

just to be sure, if you create a datasource to output your child section, is the markup ok ?

and you do select 'content: *' in your current DS ?

**Comment by andrewminton** [comment]
Yes I'm selecting `content:*`

Weirdly I've not hard coded 'formatted'  place of `$subMode` and `$curMode` variables and all is rendered correctly in the XML debug view.

**Comment by nitriques** [comment]
Ok I'll try to tackle this ...

**Comment by andrewminton** [comment]
IF you need any more information about my environment.. I'm running a build of vagrant from this repo: https://github.com/lnikkila/symphony-simple-vagrant as a test environment to build my sites locally. Thanks.

**Comment by nitriques** [comment]
Which version of Symphony is it ?

**Comment by andrewminton** [comment]
2.6.4 or 2.6.5 I believe. I'll need to check though as I'm not at my dev machine

**Comment by nitriques** [comment]
I am not able to reproduce the bug... are you running 1.0.3 ?

**Comment by nitriques** [comment]
Oh wait: Textbox are working, but not text area...

**Comment by nitriques** [comment]
But I get this:

```xml
<item id="47" level="1" max-level="-1" section-id="42" section="text-area" matched-element="">
                    <text mode=""><![CDATA[test **sasa**]]></text>
                    <text-side mode=""><![CDATA[ test  *sssasa*]]></text-side>
</item>
```

**Comment by andrewminton** [comment]
Thats what I see... unformatted. :(

**Comment by nitriques** [comment]
At least we have the same output ! haha

**Comment by andrewminton** [comment]
Which is a good thing :)

**Comment by nitriques** [comment]
I've isolated the problem down to the fact that the text area returns unformatted data when mode is null but textbox does the opposite.. meanwhile.. that's a bug..

**Comment by andrewminton** [comment]
haha! so glad it wasn't me this time :)

**Comment by nitriques** [comment]
> So textbox returns formatted by default?

If mode is null, yes.

**Comment by andrewminton** [comment]
Well there we are then.. consistency all round I see :)
