### ISSUE TITLE
Front end form submittal query

### ISSUE THREAD

**Issue by andrewminton** [DeuxHuitHuit/entry_relationship_field#56]
How do we tackle entry relationships on the front end of the site and have them reflected in the backend?

Is it just an association with ID? as with SBL?

Thanks

Andrew

**Comment by nitriques** [comment]
> Is it just an association with ID? as with SBL?

Yes. 

See https://github.com/DeuxHuitHuit/entry_relationship_field/issues/54 has the curent auto-generated markup is not valid :)

**Comment by andrewminton** [comment]
Thanks.. sorry to raise an issue to get an answer my bad.. simple lazyness on my part.

**Comment by nitriques** [comment]
> simple lazyness on my part

I do this often, no worries ;)
