### ISSUE TITLE
White border around legends on Dev install

### ISSUE THREAD

**Issue by andrewminton** [DeuxHuitHuit/entry_relationship_field#60]
Just looking over the publish settings screen and there's a white border around the extra settings legends in the markup.. see the 2 grabs below.. take a look at bottom right property inspector in Chrome..

![screen shot 2016-02-17 at 21 33 20](https://cloud.githubusercontent.com/assets/707189/13125587/4a7a4908-d5be-11e5-87a4-70fbef955e9f.png)

Background colour switched off:

![screen shot 2016-02-17 at 21 33 00](https://cloud.githubusercontent.com/assets/707189/13125596/56caf7b6-d5be-11e5-82e0-7feea2c5944b.png)

Only a minor thing but just wondered if it was intentional?

**Comment by andrewminton** [comment]
It could be browser caching... closing it for now.

**Comment by nitriques** [comment]
> It could be browser caching

Yup since there is css code to override this background (from sym core)

How do you like the new layout ?

**Comment by nitriques** [comment]
Also I've just committed 842f6a4 which should make sense.
