### ISSUE TITLE
Suggestion for a view only link in ERF options

### ISSUE THREAD

**Issue by andrewminton** [DeuxHuitHuit/entry_relationship_field#63]
Was wondering if it was worth adding a 'view' option for read only of certain relationships at all? We have 'edit', 'new', 'link', 'unlink' but maybe a 'read only' version could be helpful to some.

Thoughts?

**Comment by nitriques** [comment]
Hum, the problem is, read only view does not exists in the core and it would seems to be a hack. I would prefer to see a read only extension...

**Comment by andrewminton** [comment]
Ok, makes sense. Extend the core functionality then?

**Comment by nitriques** [comment]
Yeah, I think we would another parameter to send to each field, which would be readonly = true.

**Comment by andrewminton** [comment]
I've done something hacky with Author Roles which disables all input, textarea fields if you uncheck the ability to edit in the table. This will do for the client for now. Need to test it with ERF.

**Comment by nitriques** [comment]
it should work, as the iframe I load is the one from Symphony ;)

**Comment by andrewminton** [comment]
It does !! awesome :)
