### ISSUE TITLE
Cannot access protected property FieldEntry_relationship::$recursiveLevel (2.0.0 fatal error)

### ISSUE THREAD

**Issue by johnpuddephatt** [DeuxHuitHuit/entry_relationship_field#64]
Hello, I realise 2.0.0 isn't released so maybe it's bad etiquette to post a bug report 😕  It seems to be working really well, I'm just getting the following error:

```
Symphony Fatal Error: Cannot access protected property FieldEntry_relationship::$recursiveLevel

An error occurred in extensions/entry_relationship_field/lib/class.erfxsltutilities.php around line 153
```

This is occuring when:
- I use ERF 2.0.0
- I have sections A, B & C, where A has an ERF linking to B, and B has an ERF linking to C
- I try to use a very simple backend template following the example given on GH.

(p.s. I'm working around this by commenting out lines 151-155 of class.erfxsltutilities.php, which is fine because in my setup I'm unlikely to need to use a recursion limit.)

**Comment by nitriques** [comment]
> I realise 2.0.0 isn't released so maybe it's bad etiquette to post a bug report

Not at all! Testing edge code is a nice thing to do ;) Worst thing that can happen: I am aware of it ;)

Will check it ASAP. Thanks!

**Comment by nitriques** [comment]
@johnpuddephatt Sorry for the 6 months delay, but it is fixed now!
