### ISSUE TITLE
Unknown column 'handle' in 'field list'

### ISSUE THREAD

**Issue by andrewminton** [DeuxHuitHuit/entry_relationship_field#71]
Have come across this issue with ERF today. Symphony 2.7.0 and ERF 2.0.1.

SELECT SQL_CACHE `handle` FROM `sym_entries_data_37` WHERE `entry_id` = 9.

Weirdly there's no handle in that section as it's the ERF field. 

Any idea what could be going on here?

**Comment by andrewminton** [comment]
Updated from Beta5 and experienced this issue. Something to do with Call to undefined method `General::strpos()`

**Comment by nitriques** [comment]
Hey @andrewminton long time !

`General::strpos()` is new `2.7.0` are you sure all the files are up to date ?

**Comment by andrewminton** [comment]
Long time indeed! reverted for now as it was a pending live site. Will pull all latest to dev branch for project and update.

**Comment by nitriques** [comment]
Cool. I'll close the issue for now, but feel free to comment or open new ones when you'll upgrade.
