### ISSUE TITLE
No longer selecting `*` elements in 2.0.1

### ISSUE THREAD

**Issue by andyjones** [DeuxHuitHuit/entry_relationship_field#72]
We have many entry relationship fields that have `Include elements in Data Sources and Backend Templates` set to `*` expecting it to fetch all elements. I've updated from 2.0.0 to 2.0.1 and these elements are no longer included in the data source output.

It looks like it has something to do with the `fetchIncludeableElements()` changes introduced in 
https://github.com/DeuxHuitHuit/entry_relationship_field/commit/23d1c0bdc96a2ff3472678cba066d89dbbbd7739#diff-74f76b2010f612ced4f5aaa77da364f8R530

Is this the expected behaviour?

**Comment by andyjones** [comment]
> I've updated from 2.0.0 to 2.0.1

whoops ignore that bit, it also happens in 2.0.0. 

It returns the elements when I use `fetchIncludeableElements()` before https://github.com/DeuxHuitHuit/entry_relationship_field/commit/23d1c0bdc96a2ff3472678cba066d89dbbbd7739 and stops working after

**Comment by nitriques** [comment]
@andyjones 

Can you copy the generated xml usign the `?debug` flag please ?

**Comment by nitriques** [comment]
Wow @andyjones thanks for the detailed explanation. The change in behavior is not expected, I'll try to replicate it ASAP.

**Comment by nitriques** [comment]
Running `2.0.1` with this field

![image](https://user-images.githubusercontent.com/771169/35171993-d74c1250-fd33-11e7-8480-0afd9d46f437.png)

In the xml I get ` <content entries="1,487,346,166" sections="2,1,42,43" x-data-source-mode="*" x-field-included-elements="*">` with all the data in there.

There seems to be invalid xml in [your comment](https://github.com/DeuxHuitHuit/entry_relationship_field/issues/72#issuecomment-358926034), is it a copy paste error ?

**Comment by andyjones** [comment]
> There seems to be invalid xml in your comment, is it a copy paste error ?

yes sorry, I messed the xml up when I was snipping bits out:

```xml
<page-content>
	<section id="2" handle="pages">Pages</section>
	<entry id="3694">
		<sections entries="3708,3758,2022,3720,2039,2034,2037,3709" sections="94,96,110,66,100,107,99,86,70,85,115,88,119,98,109,111,104,101,79,113,83,90,95,69,80,117,118,74,121,102,73,92,76,77,84,78,114,72,82,68,71,75,67,97,106,112,116" x-data-source-mode="*" x-field-included-elements="*">
			<item id="2039" level="1" max-level="-1" section-id="92" section="section" matched-element="*">
				<background-colour>
					<item id="1888" handle="yellow" section-handle="colours" section-name="Colours">yellow</item>
				</background-colour>
			</item>
		</sections>
	</entry>
</page-content>
```

**Comment by andyjones** [comment]
I think it only affects ERF entries that are nested in another ERF entry. In the example above, `<sections>` and `<item>` are ERFs. It is fetching the entries for the top left ERF but not the nested `<item>` ERF. 

I'll try to get a repro.

**Comment by andyjones** [comment]
I'm able to reproduce with these steps:

1. create a new section that only contains a text field - I've given it a name and handle of `text-section`:

![image](https://user-images.githubusercontent.com/763877/35224479-028c9232-ff7d-11e7-8356-71c4aa8d9ec2.png)

2. create a new section that only contains an ERF field, available sections = the text section just created, include elements = '*'. I've named it `nested`:

![image](https://user-images.githubusercontent.com/763877/35224534-34bcf166-ff7d-11e7-9226-167d5c0e184b.png)

3. create a new top level section that only contains an ERF field, available sections = the nested section just created, include elements = '*'. I've named it `top`:

![image](https://user-images.githubusercontent.com/763877/35224581-5b111ab8-ff7d-11e7-892c-bdb59cc8879d.png)

4. Create a new entry for the top level section (you will have to create a new entry for the nested and text fields too)

When I view the debug XML for this entry, it selects the entries belonging to `top` but not `nested`.

In case it is useful, I'm now getting the debug xml with  https://gist.github.com/andyjones/d0b03cd85ad7b70e84f357bb8f320d65 so I don't have to attach the entry to a page.

**Comment by nitriques** [comment]
Hi @andyjones sorry for the late reply, been pretty busy. Can you tell me if 8c2e380 fixes the problems on your end ? Thanks again for all the precious information you shared, help me fix the problem !

**Comment by andyjones** [comment]
Works great

Thanks for fixing, appreciate it :)

**Comment by nitriques** [comment]
Awesome. The most complicated thing was already done by you, the hardest thing was to not break anything. The fix was so simple to implement. 

I'll release 2.0.2 right now. Please open other issues if you encounter anything weird!
