### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by mprofitl** [DeuxHuitHuit/entry_relationship_field#79]
It would be wonderful if entries could be sorted with drag and drop.

**Comment by nitriques** [comment]
This already exists ! Do you have a custom template ?

**Comment by mprofitl** [comment]
Indeed it works. After making the header box visible sorting works, also with my custom template. How do you feel about adding a line like that to the how to use in documentation? "Entries can be ordered only when header box option is activated"

**Comment by nitriques** [comment]
If you have a custom template, you can use the data-api to create your own custom drag target: https://github.com/DeuxHuitHuit/entry_relationship_field#data-attribute-api

Where should I add your suggestion ? In the README ?
