### ISSUE TITLE
Search for entries doesn't attach entries

### ISSUE THREAD

**Issue by pixelninja** [DeuxHuitHuit/entry_relationship_field#85]
Hello,

Firstly, very cool extension. Came across it while looking for another extension of yours.

I've set it up in a project, Symphony v2.7.10 with v2.3.1 of the extension, and the Search For Entries text input doesn't work as expected.

The autocomplete works, but when selecting an item (either click or keydown) it does nothing.

Looking at the javascript, when initialising the Suggestions plugin, it's trying to use a callback function called `editSuggestion` which when looking at the Symphony core code doesn't exist.

Are there some updates to the core needed to get this working correctly?

Cheers!

**Comment by nitriques** [comment]
Hi @pixelninja !

Thanks for the kind words!

`editSuggestion` is new in Symphony 3.0.0, so yeah, that's broken for now, sorry :(

I have been ultra busy (as always) and can't spend as much time as I want on that :(

**Comment by pixelninja** [comment]
I know the feeling!

Is the Symphony 3 codebase on a public repo somewhere? I'll see if I can port it over to my v2.7 install.

**Comment by nitriques** [comment]
@pixelninja It is in the same repro, https://github.com/symphonycms/symphony-2/tree/3.0.x but in a diff branch ;)

**Comment by pixelninja** [comment]
Awesome! Didn't think to look for v3 in the v2 repo haha

Replacing the symphony.suggestions.js file did the trick :)

Thanks @nitriques

**Comment by nitriques** [comment]
No problem ;)
